# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10

    # working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run: ls -a

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

  release:
    docker:
      - image: circleci/node:10

    # working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn publish --non-interactive --force

workflows:
  version: 2

  test_release:
    jobs:
      - test:
          filters:
            branches:
              only: master

      - release:
          requires:
            - test
